package(default_visibility = ["//visibility:public"])

cc_library(
    name = "test",
    srcs = ["test.cc"],
    hdrs = ["test.hpp"],
)

cc_test(
    name = "test_test",
    srcs = ["test_test.cc"],
    deps = ["//test"],
)
