package(default_visibility = ["//visibility:public"])

cc_library(
    name = "io",
    srcs = ["copy.cc"],
    hdrs = ["copy.hpp", "flusher.hpp", "flusher_writer.hpp",
            "reader.hpp", "sink.hpp", "source.hpp", "writer.hpp",
            "recoverer.hpp"],
    deps = ["//status"],
)
